[package]
edition = "2021"
name = "swc_plugins_core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin_import = {path = "../plugin_import"}
plugin_lock_corejs_version = {path = "../plugin_lock_corejs_version"}
plugin_lodash = {path = "../plugin_lodash"}
plugin_modernjs_ssr_loader_id = {path = "../plugin_modernjs_ssr_loader_id"}
plugin_modularize_imports = {path = "../plugin_modularize_imports"}
plugin_react_utils = {path = "../plugin_react_utils"}
plugin_remove_es_module_mark = {path = "../plugin_remove_es_module_mark"}
shared = {path = "../shared"}
swc_plugins_utils = {path = "../swc_plugins_utils"}

styled_components = "0.52.4"
styled_jsx = "0.29.4"
swc_emotion = "0.28.2"

[dev-dependencies]
insta = "1.18.2"
