[package]
edition = "2021"
name = "plugin_lock_corejs_version"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../shared"}

[dev-dependencies]
test_plugins = {path="../test_plugins"}
