[package]
name = "plugin_react_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path="../shared"}
swc_plugins_utils = {path="../swc_plugins_utils"}

[dev-dependencies]
test_plugins = {path="../test_plugins"}
glob = "0.3.0"
