[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
serde_json = "1.0.71"
serde = {version= "1.0.71", features=["derive"]}
# swc v1.3.1
# swc = "0.226.21"
# swc_ecma_parser = "0.119.9"
# swc_cached = "0.3.10"
# swc_common = "0.28.5"
# swc_ecma_visit = "0.77.5"
# swc_ecma_ast = "0.91.5"
# swc_ecma_transforms = "0.193.18"
# swc_ecma_transforms_base = "0.108.13"
# swc_ecma_transforms_react = "0.150.15"
# swc_ecma_transforms_typescript = "0.154.15"
# swc_ecma_transforms_compat = "0.131.14"
# swc_ecma_codegen = "0.124.11"
# swc_ecma_utils = "0.102.10"
# swc_ecma_minifier = "0.154.20"
# swc_ecma_preset_env = "0.169.18"
# swc_atoms = "0.4.14"
swc_ecma_transforms_testing = "0.113.13"
testing = "0.30.5"
swc_core = { features = [
  "common_concurrent",
  "ecma_ast",
  "ecma_visit",
  "ecma_loader_node",
  "ecma_loader_lru",
  "ecma_utils",
  "ecma_minifier",
  "ecma_transforms",
  "__ecma_transforms",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_transforms_optimization",
  "ecma_parser",
  "ecma_parser_typescript",
  "cached",
  "base"
], version = "0.29.5" }

[dev-dependencies]
testing_macros = "0.2.7"