name: Benchmark

env:
  DEBUG: 'napi:*'
  APP_NAME: '@modern-js/swc-plugins'
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  # https://github.com/SchrodingerZhu/snmalloc-rs
  CACHE_FRIENDLY_OFFSET: 64

'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-06
          profile: minimal
          override: true

      - name: Cache cargo
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.settings.target }}-node@14-cargo-cache

      - name: Run benchmark(Rust)
        run: cargo bench | tee output_rust.txt

      - name: Store benchmark result(Rust)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output_rust.txt
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
